version: '3.3'

services:
  dev_frontend:
    container_name: devFrontend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/frontend:latest
    ports:
      - "4200:4200"
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--port", "4200"]
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  prod_frontend:
    container_name: prodFrontend
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile.prod

  test_frontend:
    container_name: testFrontend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/frontend_test:latest
    volumes:
      - ./:/home/app
      - /home/app/node_modules
