FROM node:16

# setup workspace
RUN mkdir -p /home/app
WORKDIR /home/app

# install angular
RUN npm install -g @angular/cli

# copy dependency files
COPY package*.json /home/app/

# install dependencies
RUN npm ci
