FROM node:current-alpine3.16
RUN mkdir -p /home/app
WORKDIR /home/app

RUN apk add chromium
ENV CHROME_BIN=/usr/bin/chromium-browser

RUN npm install -g @angular/cli

COPY package*.json /home/app/
RUN npm ci
CMD ["ng", "test"]
