FROM registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/frontend:latest as build

# copy files
COPY . /home/app/
RUN ng build

# start nginx server
FROM nginx:1.21.6
EXPOSE 80
COPY --from=build /home/app/dist/frontend /usr/share/nginx/html
