version: '3.2'
services:
  dev_backend:
    container_name: devBackend
    ports:
      - '3000:3000'
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/backend:latest
    command: [ "nest", "start", "--watch" ]
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  prod_backend:
    container_name: prodBackend
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: 'Dockerfile.prod'

  test_backend:
    container_name: testBackend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/backend:latest
    command: [ "npx", "jest", "--watchAll" ]
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  test_coverage_backend:
    container_name: testCoverageBackend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/backend:latest
    command: [ "npx", "jest", "--coverage" ]
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  test_e2e_backend:
    container_name: testE2EBackend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/backend:latest
    command: [ "npx", "jest", "--config", "./test/jest-e2e.json" ]
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  lint_backend:
    container_name: lintBackend
    image: registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/frontend:latest
    command:  >
      sh -c "
        npx prettier '{src,test}/**/*.ts' --write &&
        npx eslint '{src,apps,libs,test}/**/*.ts' --fix
      "
    volumes:
      - ./:/home/app
      - /home/app/node_modules
