FROM registry.cri.epita.fr/ing/majeures/sigl/ubsi/devops/appliblanche/backend:latest as build

COPY . ./
RUN rimraf dist
RUN nest build
RUN npm prune --production

# start server
FROM node:16
WORKDIR /home/app
COPY --from=build /home/app/package.json ./package.json
COPY --from=build /home/app/package-lock.json ./package-lock.json
COPY --from=build /home/app/dist ./dist
COPY --from=build /home/app/node_modules ./node_modules
CMD ["node", "dist/main"]
